### ISSUE TITLE
I borked my install of novr with this launcher update

### ISSUE THREAD

**Issue by jazluvr449** [bfeber/HLA-NoVR-Launcher#1]
I downloaded it zip file, opened it, installed to half lafe alyx directory, I got the update/install window, ckicked it, then it only said play, so I hit play, got the game menu, but it just stopped playing after I selected my latest save. I need to uninstall the launcher and go back to how it worked before that.

Cuz I'm too stupid to install this right...lol. Wish i could have done it right. I tried it from desktop, and from steam, neither will let me play now. 

By the way, I just tried to send you $30, but the credit card page wouldn't work. Would like to donate smething for you, but page is borked too.

**Comment by bfeber** [comment]
Should be fixed now.

> By the way, I just tried to send you $30, but the credit card page wouldn't work. Would like to donate smething for you, but page is borked too.
Which one exactly? Ko-fi?

**Comment by jazluvr449** [comment]
No, it was from the GitHub page that I tried to donate to you. It had a message At the end of the info page that says “save my info”. Otherwise it wouldn’t go through. I tried w/o it saving, wouldn’t work, so I clicked on (save info)…Not comfortable with that now….dam. Thanks for getting back to me so soon when I post an issue. Sent from Mail for Windows From: Björn FeberSent: Sunday, April 30, 2023 12:45 PMTo: bfeber/HLA-NoVR-LauncherCc: jazluvr449; AuthorSubject: Re: [bfeber/HLA-NoVR-Launcher] I borked my install of novr with this launcher update (Issue #1) Should be fixed now.By the way, I just tried to send you $30, but the credit card page wouldn't work. Would like to donate smething for you, but page is borked too.Which one exactly? Ko-fi?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by jazluvr449** [comment]
I just tried to redownload and install last launcher file, I installed it, but “install” isn’t grayed out, and I got a pop-up saying some files have changed, would I like to archive them, I clicked yes, and hit play, but it still doesn’t work. I might just wait until you have finished the game to play, I have to reset binding with every update. Anyway, the launcher doesn’t specify where the launcher will be located after 1st use, desktop or steam, which of neither worked. Sent from Mail for Windows From: Björn FeberSent: Sunday, April 30, 2023 12:45 PMTo: bfeber/HLA-NoVR-LauncherCc: jazluvr449; AuthorSubject: Re: [bfeber/HLA-NoVR-Launcher] I borked my install of novr with this launcher update (Issue #1) Should be fixed now.By the way, I just tried to send you $30, but the credit card page wouldn't work. Would like to donate smething for you, but page is borked too.Which one exactly? Ko-fi?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by bfeber** [comment]
make sure you extract the newest launcher release ZIP file into a new folder, launch it, then select "Update/Install NoVR" and wait until it's done. only then click play.

**Comment by jazluvr449** [comment]
It doesn’t work for me. Can I uninstall this new launcher update? Sent from Mail for Windows From: Björn FeberSent: Sunday, April 30, 2023 5:52 PMTo: bfeber/HLA-NoVR-LauncherCc: jazluvr449; AuthorSubject: Re: [bfeber/HLA-NoVR-Launcher] I borked my install of novr with this launcher update (Issue #1) Closed #1 as completed.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by bfeber** [comment]
Verify the game files on Steam

**Comment by jazluvr449** [comment]
Actually,  in the meantime, out of frustration, I tried to go back to the 4/23 update by deleting and copying the files I have saved to desktop, it said 3 files would be reacquired, then after selecting latest save in menu, the game just crashes/ reverts to my steam library page. So then I tried to re-download and install the new update with launcher, verify files, it said 2 would be reacquired, this time the menu was low and small, like I was starting the game for 1st time, also said the settings were too high, everything was on ultra. So the game is unplayable now. I’m not blaming you, or mad, it just….the update didn’t work for me. I’m going to uninstall the game and start over, because nothing I do can fix it. I just wanted it to go back to the way it was before the new launcher update. By the way, were you able to get the donation I gave you? I feel kinda vulnerable that discord made my save my CC info…lol. But thank you very much for responding so quick  and your patience with me.  Sent from Mail for Windows From: Björn FeberSent: Sunday, April 30, 2023 6:51 PMTo: bfeber/HLA-NoVR-LauncherCc: jazluvr449; AuthorSubject: Re: [bfeber/HLA-NoVR-Launcher] I borked my install of novr with this launcher update (Issue #1) Verify the game files on Steam—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by jazluvr449** [comment]
Hi, I been playing the game almost non-stop. It’s addicting! As expected, the game is still in development, it’s been a while since you responded to this issue. I’m not using the launcher, as I don’t know if it will keep my keyboard binding, as well as game progress. I have 2 major problems right now. I don’t know how to equip the shotgun grenade launcher, and I keep getting a “noclip” area as I progress through arms race after I kill the 1st gunner inside the wharehouse. Can you help me? Sent from Mail for Windows From: Björn FeberSent: Sunday, April 30, 2023 6:51 PMTo: bfeber/HLA-NoVR-LauncherCc: jazluvr449; AuthorSubject: Re: [bfeber/HLA-NoVR-Launcher] I borked my install of novr with this launcher update (Issue #1) Verify the game files on Steam—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
