### ISSUE TITLE
Request from Chinese player

### ISSUE THREAD

**Issue by AbrnYa** [bfeber/HLA-NoVR-Launcher#16]
Hello, I am a Chinese enthusiast and I really enjoy this project.
Can I use Vue+Tauri+Trust for secondary development, as it may not be possible to download and install properly in China; Can I redevelop, build and set up server clone downloads in Chinese Mainland?

**Comment by bfeber** [comment]
No problem, just respect the LGPL license

**Comment by AbrnYa** [comment]
Thank you.
