### ISSUE TITLE
Main Menu buttons dont work at all

### ISSUE THREAD

**Issue by ellie12134** [bfeber/HLA-NoVR-Launcher#21]
Most of the Main Menu buttons dont work at all, no loading, no continue. so I cannot resume my progress
Options work tho

this used to happen to me on the 18dec build of the launcher, so I regressed back to the 17dec build and it finally worked until last night, Saved the game at "The Northern Star", went to sleep and right now it doesn't work anymore

**Comment by WhoseKnee** [comment]
Same issue but for me, it happens after saving and loading in to Quarantine Zone. Cursor would not click into the game and pressing Esc does not bring up the menu. Keyboard input still functions. Restarting NoVR does not bring up the menu in the home screen. Again, keyboard works there as I press C to launch the VConsole.

Things I tried:
1) **Redownloaded NoVR**, removed all files and extract into same folder - _does not work, same issue._ 
2) **Revert to older versions**, removed all files and extract into same folder - _does not work, same issue._ 
3) **Validate integrity of HL Alyx through Steam** - _does not work, same issue._

**Comment by Sergeant61** [comment]
Same problem

**Comment by Sergeant61** [comment]
Edit: The problem was fixed when I ran it as administrator.
