### ISSUE TITLE
Cannot run main executable from Zip file

### ISSUE THREAD

**Issue by Verault** [bfeber/HLA-NoVR-Launcher#22]
I guess Im late to the game in discovering this mod. I just bought HL ALYX as it was on sale. I Downloaded the ZIP package and extracted and tried to run the HLA-NoVR-Launcher.exe file I get the attached error. I have tried several times. All the same error. Please advise.
![hla-noVR error](https://github.com/bfeber/HLA-NoVR-Launcher/assets/64697404/3f68f988-e28c-4eed-ab77-02ba6aeb81cb)

**Comment by bfeber** [comment]
Windows 7 is not supported, see #18 for details
