### ISSUE TITLE
Can't open the very first canister with multitool

### ISSUE THREAD

**Issue by TheEpicTimmy** [bfeber/HLA-NoVR-Launcher#25]
First canister you encounter before entering the quarantine zone, when I use the multitool red and blue dots appear on the screen and I can't open the canister to get the item I need to use to open the big metal door.

**Comment by ctarbet00** [comment]
I'm stuck here as well. I can shoot and activate the multitool and crouch, but nothing else works. I can't move or affect the red and blue dots.

**Comment by sgjohnson1981** [comment]
The issue for me was the alternative instructions didn't initially pop up to tell me what to do with the dots. I think I may have been stuck clipped but didn't realize it. I just chose a previous save point and walked back to it. Somehow the second time it finally notified me how to move the dots.

**Comment by bfeber** [comment]
Puzzle is removed for now
