### ISSUE TITLE
Add custom launch options

### ISSUE THREAD

**Issue by landsman** [bfeber/HLA-NoVR-Launcher#4]
Hey, do you have any idea how to set up the game "launch options" to run NoVR Launcher instead of game? It would be wonderful.

**Comment by TarekLP** [comment]
You can add the Launcher as a non Steam Game, or make a shortcut from the Exe

**Comment by bfeber** [comment]
I'm going to add a section for launch options in the launcher soon

**Comment by bfeber** [comment]
Added
