### ISSUE TITLE
launcher has fps issues when moving mouse over and away from buttons

### ISSUE THREAD

**Issue by zoulztealer** [bfeber/HLA-NoVR-Launcher#7]
the launcher has some kind of fps issues in connection with the mouse being overed over the buttons.

when the mouse cursor is pointed away from a button fps drop to about 26 (screenshot 1).

when the mouse cursor is pointed over one of the buttons fps jump up quickly to 60 again for a short period of time then drop to about 26 again. jumps can be seen in frame time graph (screenshot 2).

when the mouse cursor is moved fast back and forth over the buttons the fps stay constantly on 60 fps (screenshot 3).

whenever the mouse cursor is pointed over a button fps return to normal for a short time then drop again buy some unknown load. it looks like some unknown load is going on in the launcher that drop its fps.

![bug 1](https://github.com/bfeber/HLA-NoVR-Launcher/assets/42149920/22e805cf-9064-4ec2-bd7b-e5f7a2ba4931)
![bug2](https://github.com/bfeber/HLA-NoVR-Launcher/assets/42149920/7c0f6c92-c321-4478-a666-d575440274a4)
![bug3](https://github.com/bfeber/HLA-NoVR-Launcher/assets/42149920/51cc2c9b-305f-481c-9e08-7b43456e5aa1)

**Comment by bfeber** [comment]
That's completely normal, since the video is 24 FPS and the UI is your monitor's refresh rate.
