### ISSUE TITLE
launcher needs button option to uninstall, simplify update logic

### ISSUE THREAD

**Issue by zoulztealer** [bfeber/HLA-NoVR-Launcher#9]
launcher is missing a uninstall button.

update function should be changed and simplified so that the launcher checks the currently installed version and does not update if installed version is the same as from update / github repository.

currently update / install always prompts the user anew for the game folder and overwrites already present files. this should be avoided by a check of the version that is already installed.

**Comment by bfeber** [comment]
The launcher now updates the mod automatically like suggested. An uninstall button isn't planned, since the mod is quite small and you can just play the VR version if you don't use the launcher
